from __future__ import annotations

"""M4Y Bellman-trace evidence and held-out continuation coverage.

M4X can prove a support-gap bound only inside a declared continuation region.
M4Y turns that declaration into auditable evidence plumbing. It freezes complete
50-state Bellman iterates, normalizes every iterate to one relative-value gauge,
derives M4X anchors from a training prefix with deterministic farthest-point
coverage, and evaluates future/held-out iterates without changing the family.

The same held-out continuation vectors can be used to benchmark M4W's
continuation-independent outcome model. No threshold is invented here: M4Y
reports distances and prediction errors. Strategic promotion remains blocked
until real outer-Bellman traces and explicit downstream acceptance thresholds
exist.
"""

from dataclasses import dataclass
import hashlib
import json
import math
from typing import Mapping, Protocol, Sequence

from engine import Board
from fantasy_fantasy_payoff import continuation_fingerprint
from hu_continuation import HUContinuationState, all_states, normalize_relative_values
from m4w_outcome_model import FantasyOutcomeExample, q_from_outcome
from m4x_robust_support import (
    ContinuationFamily,
    RobustFantasySupport,
    RobustSupportAudit,
    audit_robust_support,
    continuation_region_membership,
    evaluate_robust_support_at,
    freeze_continuation_family,
    linf_distance,
    robust_support_gap_bound,
)

TRACE_SCHEMA = "openofc-m4y-bellman-trace-v1"
COVERAGE_SCHEMA = "openofc-m4y-trace-coverage-v1"
MODEL_BENCHMARK_SCHEMA = "openofc-m4y-m4w-heldout-benchmark-v1"
SUPPORT_TRACE_SCHEMA = "openofc-m4y-support-trace-audit-v1"
AUTHORITY = "SHA_BOUND_BELLMAN_TRACE_HELDOUT_EVIDENCE"
EVIDENCE_REAL = "REAL_BELLMAN_ITERATES"
EVIDENCE_FIXTURE = "SYNTHETIC_TEST_FIXTURE"
EVIDENCE_KINDS = (EVIDENCE_REAL, EVIDENCE_FIXTURE)
EPS = 1e-9


def _canonical_bytes(payload: object) -> bytes:
    return json.dumps(
        payload, sort_keys=True, separators=(",", ":"), allow_nan=False
    ).encode("utf-8")


def _sha(payload: Mapping[str, object]) -> str:
    raw = dict(payload)
    raw.pop("sha256", None)
    return hashlib.sha256(_canonical_bytes(raw)).hexdigest()


def _is_sha256(value: str) -> bool:
    if len(value) != 64:
        return False
    try:
        int(value, 16)
    except ValueError:
        return False
    return True


@dataclass(frozen=True)
class BellmanTracePoint:
    index: int
    label: str
    gain_anchor: float
    values: tuple[tuple[HUContinuationState, float], ...]
    continuation_sha256: str

    def as_mapping(self) -> dict[HUContinuationState, float]:
        return {state: float(value) for state, value in self.values}


@dataclass(frozen=True)
class BellmanTrace:
    points: tuple[BellmanTracePoint, ...]
    provenance: str
    oracle_manifest_sha256: str
    normalization_reference: str
    evidence_kind: str
    sha256: str
    schema: str = TRACE_SCHEMA
    authority: str = AUTHORITY

    @property
    def is_real(self) -> bool:
        return self.evidence_kind == EVIDENCE_REAL


def freeze_bellman_trace(
    iterates: Sequence[Mapping[HUContinuationState, float]],
    *,
    provenance: str,
    oracle_manifest_sha256: str,
    evidence_kind: str,
    normalization_reference: HUContinuationState | None = None,
) -> BellmanTrace:
    """Freeze ordered complete Bellman images into one relative-value gauge.

    `gain_anchor` records the value subtracted from each raw Bellman image.
    This is the average-reward relative-value normalization primitive; M4Y does
    not claim that the supplied sequence was generated by a correct Bellman
    oracle. That claim belongs to `evidence_kind` + external provenance.
    """
    rows = tuple(iterates)
    if not rows:
        raise ValueError("M4Y Bellman trace requires at least one iterate")
    if evidence_kind not in EVIDENCE_KINDS:
        raise ValueError("unsupported M4Y evidence kind")
    if not str(provenance).strip():
        raise ValueError("M4Y trace provenance must be non-empty")
    if not _is_sha256(str(oracle_manifest_sha256)):
        raise ValueError("oracle_manifest_sha256 must be a 64-hex SHA-256")

    reference = normalization_reference or HUContinuationState(0, 0, 0)
    if reference not in set(all_states()):
        raise ValueError("M4Y normalization reference is outside the 50-state catalog")

    points: list[BellmanTracePoint] = []
    for index, raw_values in enumerate(rows):
        checked, _raw_sha = continuation_fingerprint(raw_values)
        if any(not math.isfinite(float(value)) for value in checked.values()):
            raise ValueError("M4Y Bellman iterate contains non-finite value")
        gain, normalized = normalize_relative_values(checked, reference=reference)
        normalized_checked, normalized_sha = continuation_fingerprint(normalized)
        if abs(float(normalized_checked[reference])) > EPS:
            raise AssertionError("M4Y normalization failed to set reference gauge to zero")
        points.append(
            BellmanTracePoint(
                index=index,
                label=f"iter-{index:06d}",
                gain_anchor=float(gain),
                values=tuple(
                    (state, float(normalized_checked[state]))
                    for state in sorted(normalized_checked)
                ),
                continuation_sha256=normalized_sha,
            )
        )

    payload: dict[str, object] = {
        "schema": TRACE_SCHEMA,
        "authority": AUTHORITY,
        "provenance": str(provenance),
        "oracle_manifest_sha256": str(oracle_manifest_sha256).lower(),
        "normalization_reference": reference.as_key(),
        "evidence_kind": evidence_kind,
        "points": [
            {
                "index": point.index,
                "label": point.label,
                "gain_anchor": point.gain_anchor,
                "continuation_sha256": point.continuation_sha256,
            }
            for point in points
        ],
    }
    return BellmanTrace(
        points=tuple(points),
        provenance=str(provenance),
        oracle_manifest_sha256=str(oracle_manifest_sha256).lower(),
        normalization_reference=reference.as_key(),
        evidence_kind=evidence_kind,
        sha256=_sha(payload),
    )


def _nearest_distance(
    point: BellmanTracePoint,
    anchors: Sequence[BellmanTracePoint],
) -> tuple[float, int]:
    if not anchors:
        raise ValueError("nearest-distance query requires at least one anchor")
    rows = [
        (
            linf_distance(point.as_mapping(), anchor.as_mapping()),
            anchor.index,
        )
        for anchor in anchors
    ]
    return min(rows, key=lambda row: (row[0], row[1]))


@dataclass(frozen=True)
class TraceFamilyDerivation:
    family: ContinuationFamily
    training_indices: tuple[int, ...]
    holdout_indices: tuple[int, ...]
    anchor_indices: tuple[int, ...]
    training_cover_radius_linf: float
    trace_sha256: str
    selection: str = "DETERMINISTIC_FARTHEST_POINT_LINF_TRAIN_PREFIX"


def derive_trace_family(
    trace: BellmanTrace,
    *,
    training_points: int,
    anchor_count: int,
) -> TraceFamilyDerivation:
    """Derive M4X family from a training prefix without looking at holdout rows.

    Radius is the exact maximum nearest-anchor L-infinity distance over the
    training prefix. Holdout iterates are never used to choose anchors or radius.
    """
    total = len(trace.points)
    if training_points <= 0 or training_points > total:
        raise ValueError("training_points must be in [1, trace length]")
    if anchor_count <= 0 or anchor_count > training_points:
        raise ValueError("anchor_count must be in [1, training_points]")

    training = trace.points[:training_points]
    selected: list[BellmanTracePoint] = [training[0]]
    selected_indices = {training[0].index}

    while len(selected) < anchor_count:
        candidates = [p for p in training if p.index not in selected_indices]
        chosen = max(
            candidates,
            key=lambda point: (
                _nearest_distance(point, selected)[0],
                -point.index,
            ),
        )
        selected.append(chosen)
        selected_indices.add(chosen.index)

    radius = max(_nearest_distance(point, selected)[0] for point in training)
    named = {
        f"trace-{point.index:06d}": point.as_mapping()
        for point in selected
    }
    family = freeze_continuation_family(
        named,
        radius_linf=float(radius),
        provenance=(
            "M4Y real Bellman trace training-prefix farthest-point family"
            if trace.is_real
            else "M4Y synthetic regression fixture family"
        ),
        source_sha256=trace.sha256,
        normalization_reference=next(
            state for state in all_states()
            if state.as_key() == trace.normalization_reference
        ),
    )
    return TraceFamilyDerivation(
        family=family,
        training_indices=tuple(point.index for point in training),
        holdout_indices=tuple(point.index for point in trace.points[training_points:]),
        anchor_indices=tuple(point.index for point in selected),
        training_cover_radius_linf=float(radius),
        trace_sha256=trace.sha256,
    )


@dataclass(frozen=True)
class TraceCoveragePoint:
    index: int
    label: str
    nearest_anchor: str
    distance_linf: float
    inside_training_region: bool


@dataclass(frozen=True)
class TraceCoverageReport:
    trace_sha256: str
    family_sha256: str
    training_points: int
    holdout_points: int
    training_cover_radius_linf: float
    holdout_inside_fraction: float
    max_holdout_distance_linf: float
    mean_holdout_distance_linf: float
    holdout: tuple[TraceCoveragePoint, ...]
    status: str
    sha256: str
    schema: str = COVERAGE_SCHEMA
    authority: str = AUTHORITY


def assess_trace_coverage(
    trace: BellmanTrace,
    derivation: TraceFamilyDerivation,
) -> TraceCoverageReport:
    if derivation.trace_sha256 != trace.sha256:
        raise ValueError("M4Y family derivation belongs to a different trace")
    holdout = [trace.points[index] for index in derivation.holdout_indices]
    rows: list[TraceCoveragePoint] = []
    for point in holdout:
        membership = continuation_region_membership(
            derivation.family, point.as_mapping()
        )
        rows.append(
            TraceCoveragePoint(
                index=point.index,
                label=point.label,
                nearest_anchor=membership.nearest_anchor,
                distance_linf=membership.distance_linf,
                inside_training_region=membership.inside,
            )
        )

    if rows:
        inside_count = sum(int(row.inside_training_region) for row in rows)
        fraction = inside_count / float(len(rows))
        max_distance = max(row.distance_linf for row in rows)
        mean_distance = sum(row.distance_linf for row in rows) / float(len(rows))
    else:
        fraction = 0.0
        max_distance = 0.0
        mean_distance = 0.0

    if trace.evidence_kind == EVIDENCE_FIXTURE:
        status = "SYNTHETIC_FIXTURE_ONLY"
    elif not rows:
        status = "REAL_TRACE_NO_HOLDOUT"
    elif all(row.inside_training_region for row in rows):
        status = "REAL_TRACE_HOLDOUT_COVERED"
    else:
        status = "REAL_TRACE_HOLDOUT_ESCAPE_OBSERVED"

    payload: dict[str, object] = {
        "schema": COVERAGE_SCHEMA,
        "authority": AUTHORITY,
        "trace_sha256": trace.sha256,
        "family_sha256": derivation.family.sha256,
        "training_points": len(derivation.training_indices),
        "holdout_points": len(rows),
        "training_cover_radius_linf": derivation.training_cover_radius_linf,
        "holdout_inside_fraction": fraction,
        "max_holdout_distance_linf": max_distance,
        "mean_holdout_distance_linf": mean_distance,
        "status": status,
        "holdout": [
            {
                "index": row.index,
                "nearest_anchor": row.nearest_anchor,
                "distance_linf": row.distance_linf,
                "inside_training_region": row.inside_training_region,
            }
            for row in rows
        ],
    }
    return TraceCoverageReport(
        trace_sha256=trace.sha256,
        family_sha256=derivation.family.sha256,
        training_points=len(derivation.training_indices),
        holdout_points=len(rows),
        training_cover_radius_linf=derivation.training_cover_radius_linf,
        holdout_inside_fraction=float(fraction),
        max_holdout_distance_linf=float(max_distance),
        mean_holdout_distance_linf=float(mean_distance),
        holdout=tuple(rows),
        status=status,
        sha256=_sha(payload),
    )


class OutcomePredictor(Protocol):
    def predict_features(
        self,
        state_features: Sequence[int],
        action_features: Sequence[int],
    ) -> tuple[float, tuple[float, ...]]: ...


@dataclass(frozen=True)
class M4WHeldoutBenchmark:
    trace_sha256: str
    continuation_points: int
    examples: int
    q_observations: int
    mean_immediate_abs_error: float
    max_immediate_abs_error: float
    mean_outcome_brier: float
    mean_outcome_cross_entropy: float
    mean_q_abs_error: float
    max_q_abs_error: float
    status: str
    sha256: str
    schema: str = MODEL_BENCHMARK_SCHEMA
    authority: str = AUTHORITY


def benchmark_m4w_on_trace(
    model: OutcomePredictor,
    examples: Sequence[FantasyOutcomeExample],
    trace: BellmanTrace,
    *,
    point_indices: Sequence[int],
) -> M4WHeldoutBenchmark:
    """Benchmark M4W labels/model over frozen continuation vectors, threshold-free."""
    rows = tuple(examples)
    indices = tuple(int(index) for index in point_indices)
    if not rows or not indices:
        raise ValueError("M4Y M4W benchmark requires examples and continuation points")
    if len(set(indices)) != len(indices):
        raise ValueError("M4Y benchmark point indices must be unique")
    if any(index < 0 or index >= len(trace.points) for index in indices):
        raise ValueError("M4Y benchmark point index is outside trace")

    immediate_errors: list[float] = []
    briers: list[float] = []
    cross_entropies: list[float] = []
    q_errors: list[float] = []

    for example in rows:
        pred_immediate, pred_distribution = model.predict_features(
            example.state_features, example.action_features
        )
        pred = tuple(float(value) for value in pred_distribution)
        if len(pred) != len(example.next_mode_distribution):
            raise ValueError("M4W predictor returned wrong outcome dimension")
        if any(not math.isfinite(value) or value < 0.0 for value in pred):
            raise ValueError("M4W predictor returned invalid outcome probabilities")
        total = sum(pred)
        if total <= 0.0:
            raise ValueError("M4W predictor returned zero probability mass")
        pred = tuple(value / total for value in pred)
        if not math.isfinite(float(pred_immediate)):
            raise ValueError("M4W predictor returned non-finite immediate value")

        immediate_errors.append(abs(float(pred_immediate) - example.immediate_target))
        briers.append(
            sum(
                (prediction - target) ** 2
                for prediction, target in zip(
                    pred, example.next_mode_distribution, strict=True
                )
            ) / float(len(pred))
        )
        cross_entropies.append(
            -sum(
                target * math.log(max(1e-15, prediction))
                for prediction, target in zip(
                    pred, example.next_mode_distribution, strict=True
                )
                if target > 0.0
            )
        )

        meta = HUContinuationState(example.current_button, 14, 14)
        for index in indices:
            values = trace.points[index].as_mapping()
            exact_q = q_from_outcome(
                example.immediate_target,
                example.next_mode_distribution,
                current_meta=meta,
                player=example.player,
                continuation_values=values,
            )
            predicted_q = q_from_outcome(
                float(pred_immediate),
                pred,
                current_meta=meta,
                player=example.player,
                continuation_values=values,
            )
            q_errors.append(abs(float(predicted_q) - float(exact_q)))

    status = (
        "SYNTHETIC_FIXTURE_ONLY"
        if trace.evidence_kind == EVIDENCE_FIXTURE
        else "REAL_TRACE_MODEL_BENCHMARK_NO_PROMOTION_THRESHOLD"
    )
    mean = lambda values: sum(values) / float(len(values))
    payload: dict[str, object] = {
        "schema": MODEL_BENCHMARK_SCHEMA,
        "authority": AUTHORITY,
        "trace_sha256": trace.sha256,
        "continuation_indices": indices,
        "examples": len(rows),
        "q_observations": len(q_errors),
        "mean_immediate_abs_error": mean(immediate_errors),
        "max_immediate_abs_error": max(immediate_errors),
        "mean_outcome_brier": mean(briers),
        "mean_outcome_cross_entropy": mean(cross_entropies),
        "mean_q_abs_error": mean(q_errors),
        "max_q_abs_error": max(q_errors),
        "status": status,
    }
    return M4WHeldoutBenchmark(
        trace_sha256=trace.sha256,
        continuation_points=len(indices),
        examples=len(rows),
        q_observations=len(q_errors),
        mean_immediate_abs_error=float(mean(immediate_errors)),
        max_immediate_abs_error=float(max(immediate_errors)),
        mean_outcome_brier=float(mean(briers)),
        mean_outcome_cross_entropy=float(mean(cross_entropies)),
        mean_q_abs_error=float(mean(q_errors)),
        max_q_abs_error=float(max(q_errors)),
        status=status,
        sha256=_sha(payload),
    )


@dataclass(frozen=True)
class SupportTracePoint:
    index: int
    inside_training_region: bool
    distance_linf: float
    actual_support_gap: float
    theorem_gap_upper_bound: float | None
    theorem_holds: bool | None


@dataclass(frozen=True)
class SupportTraceAudit:
    trace_sha256: str
    family_sha256: str
    support_sha256: str
    anchor_audit_sha256: str
    points: tuple[SupportTracePoint, ...]
    max_actual_support_gap: float
    escapes: int
    status: str
    sha256: str
    schema: str = SUPPORT_TRACE_SCHEMA
    authority: str = AUTHORITY


def audit_support_on_trace(
    support: RobustFantasySupport,
    opponent_board: Board,
    derivation: TraceFamilyDerivation,
    trace: BellmanTrace,
    *,
    point_indices: Sequence[int],
    anchor_audit: RobustSupportAudit | None = None,
) -> SupportTraceAudit:
    """Audit held-out trace points against M4N and validate the M4X theorem."""
    if derivation.trace_sha256 != trace.sha256:
        raise ValueError("M4Y support audit trace/family mismatch")
    family = derivation.family
    if support.family_sha256 != family.sha256:
        raise ValueError("M4Y support belongs to a different continuation family")
    audit = anchor_audit or audit_robust_support(support, opponent_board, family)
    if audit.family_sha256 != family.sha256 or audit.support_sha256 != support.sha256:
        raise ValueError("M4Y anchor audit does not match support/family")

    indices = tuple(int(index) for index in point_indices)
    if not indices or len(set(indices)) != len(indices):
        raise ValueError("M4Y support trace audit needs unique point indices")
    if any(index < 0 or index >= len(trace.points) for index in indices):
        raise ValueError("M4Y support trace index is outside trace")

    rows: list[SupportTracePoint] = []
    for index in indices:
        point = trace.points[index]
        values = point.as_mapping()
        membership = continuation_region_membership(family, values)
        actual = evaluate_robust_support_at(support, opponent_board, values)
        if membership.inside:
            theorem = robust_support_gap_bound(audit, family, values)
            holds = actual.support_gap <= theorem.gap_upper_bound + EPS
            if not holds:
                raise AssertionError("M4X support-gap theorem violated on M4Y trace point")
            bound: float | None = theorem.gap_upper_bound
        else:
            holds = None
            bound = None
        rows.append(
            SupportTracePoint(
                index=index,
                inside_training_region=membership.inside,
                distance_linf=membership.distance_linf,
                actual_support_gap=actual.support_gap,
                theorem_gap_upper_bound=bound,
                theorem_holds=holds,
            )
        )

    escapes = sum(int(not row.inside_training_region) for row in rows)
    if trace.evidence_kind == EVIDENCE_FIXTURE:
        status = "SYNTHETIC_FIXTURE_ONLY"
    elif escapes:
        status = "REAL_TRACE_ESCAPE_REQUIRES_FAMILY_EXPANSION"
    else:
        status = "REAL_TRACE_REGION_AUDITED_NO_STRATEGIC_PROMOTION"

    payload: dict[str, object] = {
        "schema": SUPPORT_TRACE_SCHEMA,
        "authority": AUTHORITY,
        "trace_sha256": trace.sha256,
        "family_sha256": family.sha256,
        "support_sha256": support.sha256,
        "anchor_audit_sha256": audit.sha256,
        "indices": indices,
        "max_actual_support_gap": max(row.actual_support_gap for row in rows),
        "escapes": escapes,
        "status": status,
    }
    return SupportTraceAudit(
        trace_sha256=trace.sha256,
        family_sha256=family.sha256,
        support_sha256=support.sha256,
        anchor_audit_sha256=audit.sha256,
        points=tuple(rows),
        max_actual_support_gap=float(max(row.actual_support_gap for row in rows)),
        escapes=escapes,
        status=status,
        sha256=_sha(payload),
    )
