from __future__ import annotations

from dataclasses import dataclass
import hashlib

from fantasy_fantasy_payoff import continuation_fingerprint
from hu_continuation import HUContinuationState, all_states, zero_continuation_values
from m4x_robust_support import freeze_continuation_family
from m4z_outer_bellman import OneHandOracleResult, default_blocked_registry
from m5e_fantasy_route_certification import (
    CertifiedFantasyFantasyOracle,
    ROUTE_BLOCKED,
    ROUTE_CERTIFIED,
    certification_route,
    freeze_certification,
    freeze_route_evidence,
    register_certified_fantasy_routes,
    validate_route_evidence,
)


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _family(radius: float = 0.5):
    return freeze_continuation_family(
        {"anchor-zero": zero_continuation_values()},
        radius_linf=radius,
        provenance="M5E deterministic regression family",
        source_sha256=_sha("m5e-family-source"),
    )


def _passing_evidence(state, values, family, oracle_id, model_sha):
    return freeze_route_evidence(
        state,
        values,
        family,
        oracle_id=oracle_id,
        model_sha256=model_sha,
        implementation_sha256=_sha("m5e-implementation"),
        support_gap=0.02,
        support_deviation_gain=0.03,
        model_q_mae=0.01,
        model_q_max_error=0.04,
        standard_error=0.02,
        heldout_worlds=128,
        heldout_seeds=4,
        max_support_gap=0.05,
        max_support_deviation_gain=0.05,
        max_model_q_mae=0.02,
        max_model_q_error=0.05,
        max_standard_error=0.03,
        reference_authority="M4N_EXACT_PLUS_M4P_SUPPORT_DEVIATION_HELDOUT",
        provenance="independent held-out regression fixture",
    )


@dataclass(frozen=True)
class FakeSnapshot:
    model_sha256: str


class FakeFantasyOracle:
    def __init__(self, family, model_sha: str, oracle_id: str) -> None:
        self.family = family
        self.snapshot = FakeSnapshot(model_sha256=model_sha)
        self.oracle_id = oracle_id

    def evaluate(self, state, continuation_values) -> OneHandOracleResult:
        _checked, sha = continuation_fingerprint(continuation_values)
        return OneHandOracleResult(
            state=state,
            p0_value=0.375,
            continuation_sha256=sha,
            oracle_id=self.oracle_id,
            samples=64,
            standard_error=0.02,
        )


def test_passing_evidence_freezes_exact_v_certificate_and_registry_route() -> None:
    state = HUContinuationState(0, 14, 14)
    values = zero_continuation_values()
    family = _family()
    model_sha = _sha("m5e-model")
    oracle_id = "m5a-fantasy-fixture"
    evidence = _passing_evidence(state, values, family, oracle_id, model_sha)
    assert evidence["passed"] is True
    validate_route_evidence(evidence)
    manifest = freeze_certification(
        [evidence],
        values,
        family,
        source_report_sha256=_sha("m5e-heldout-report"),
        provenance="M5E held-out certification fixture",
    )
    assert manifest["certified_route_count"] == 1
    assert certification_route(manifest, state, values) == ROUTE_CERTIFIED

    delegate = FakeFantasyOracle(family, model_sha, oracle_id)
    wrapped = CertifiedFantasyFantasyOracle(delegate, state, manifest)
    result = wrapped.evaluate(state, values)
    assert result.p0_value == 0.375
    assert result.oracle_id.startswith("m5e:")

    registry = default_blocked_registry()
    count = register_certified_fantasy_routes(
        registry, manifest, fantasy_oracle=delegate
    )
    assert count == 1
    frozen = registry.freeze_manifest()
    assert frozen.ready_certified == 1
    assert frozen.blocked == 49


def test_changed_continuation_sha_is_blocked_even_inside_family() -> None:
    state = HUContinuationState(1, 14, 15)
    values = zero_continuation_values()
    family = _family(radius=0.5)
    model_sha = _sha("m5e-model-2")
    oracle_id = "m5a-fantasy-fixture-2"
    evidence = _passing_evidence(state, values, family, oracle_id, model_sha)
    manifest = freeze_certification(
        [evidence],
        values,
        family,
        source_report_sha256=_sha("m5e-report-2"),
        provenance="exact continuation SHA regression",
    )
    changed = zero_continuation_values()
    target = HUContinuationState(0, 14, 14)
    changed[target] = 0.1
    # 0.1 is inside the declared 0.5 M4X region, but the exact M5E route
    # certificate is still intentionally stale and must be regenerated by M5D.
    assert certification_route(manifest, state, changed) == ROUTE_BLOCKED


def test_failed_metric_cannot_be_certified() -> None:
    state = HUContinuationState(0, 16, 17)
    values = zero_continuation_values()
    family = _family()
    bad = freeze_route_evidence(
        state,
        values,
        family,
        oracle_id="bad-fixture",
        model_sha256=_sha("bad-model"),
        implementation_sha256=_sha("bad-implementation"),
        support_gap=0.20,
        support_deviation_gain=0.01,
        model_q_mae=0.01,
        model_q_max_error=0.01,
        standard_error=0.01,
        heldout_worlds=32,
        heldout_seeds=2,
        max_support_gap=0.05,
        max_support_deviation_gain=0.05,
        max_model_q_mae=0.05,
        max_model_q_error=0.05,
        max_standard_error=0.05,
        reference_authority="exact-teacher-fixture",
        provenance="expected failure",
    )
    assert bad["passed"] is False
    try:
        freeze_certification(
            [bad],
            values,
            family,
            source_report_sha256=_sha("bad-report"),
            provenance="must fail",
        )
    except ValueError as exc:
        assert "refuses to certify failed" in str(exc)
    else:
        raise AssertionError("M5E certified failed strategic evidence")


def test_outside_m4x_region_and_delegate_drift_fail_closed() -> None:
    state = HUContinuationState(1, 17, 17)
    family = _family(radius=0.0)
    changed = zero_continuation_values()
    changed[HUContinuationState(0, 14, 14)] = 0.01
    try:
        _passing_evidence(
            state,
            changed,
            family,
            "outside-fixture",
            _sha("outside-model"),
        )
    except ValueError as exc:
        assert "outside the M4X support region" in str(exc)
    else:
        raise AssertionError("M5E accepted continuation outside M4X region")

    values = zero_continuation_values()
    good_model_sha = _sha("good-model")
    evidence = _passing_evidence(
        state, values, family, "stable-oracle", good_model_sha
    )
    manifest = freeze_certification(
        [evidence],
        values,
        family,
        source_report_sha256=_sha("stable-report"),
        provenance="delegate drift regression",
    )
    drifted = FakeFantasyOracle(family, _sha("different-model"), "stable-oracle")
    try:
        CertifiedFantasyFantasyOracle(drifted, state, manifest)
    except ValueError as exc:
        assert "model SHA" in str(exc)
    else:
        raise AssertionError("M5E accepted delegate model drift")


def main() -> None:
    test_passing_evidence_freezes_exact_v_certificate_and_registry_route()
    test_changed_continuation_sha_is_blocked_even_inside_family()
    test_failed_metric_cannot_be_certified()
    test_outside_m4x_region_and_delegate_drift_fail_closed()
    print("OPENOFC_M5E_FANTASY_ROUTE_CERTIFICATION_GATE=PASS")


if __name__ == "__main__":
    main()
